// SPDX-FileCopyrightText: Copyright 2025 Securosys SA
// SPDX-License-Identifier: Apache-2.0

apply plugin: 'java'
apply plugin: 'org.springframework.boot'

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation project(path: ':fireblocks-service')

	runtimeOnly 'com.h2database:h2'
	runtimeOnly 'org.mariadb.jdbc:mariadb-java-client'
}

tasks.named('assemble').configure {
	doLast {
		println 'Copying resources...'
		copy {
			from project(':fireblocks-service').layout.buildDirectory.dir('resources/main').get()
			into layout.buildDirectory.dir('resources/main').get()
			include 'logback.xml'
		}
	}
}
