// SPDX-FileCopyrightText: Copyright 2025 Securosys SA
// SPDX-License-Identifier: Apache-2.0

buildscript {
	ext {
		repoUser = findProperty('repoUser') ?: System.env.BINREPO_USER
		repoPass = findProperty('repoPass') ?: System.env.BINREPO_TOKEN
	}
	repositories {
		maven {
			url 'https://binrepo.adnovum.ch/artifactory/adn-public-maven-vi'
			credentials {
				username = repoUser
				password = repoPass
			}
		}
	}
}

apply plugin: 'base'

configurations {
	deployment
}

def dockerImageName = System.getenv("DOCKER_IMAGE_NAME");
def artifactoryUrl= System.getenv("JFROG_ARTIFACTORY_URL");
def internalPrefix = System.getenv("INTERNAL_PREFIX");

if(internalPrefix==null){
    internalPrefix=""
}
def artifactoryRealName= internalPrefix+System.getenv("JFROG_REPOSITORY_REAL_NAME");

dependencies {
	deployment project(path: ':fireblocks-application', configuration: 'bootArchives')
}

tasks.register('unpackBootJar', Copy) {
	dependsOn configurations.deployment
	from(zipTree(configurations.deployment.files.first()))
	into layout.buildDirectory.dir('dependency')
	doLast {
		println "Unzipping ${configurations.deployment.files.first()}"
	}
}

tasks.register('prepareDockerContext', Copy) {
	dependsOn tasks.named('unpackBootJar')
	into layout.buildDirectory.dir('docker')
	from("Dockerfile") { into '.' }
	from(layout.buildDirectory.dir('dependency/BOOT-INF/lib')) { into 'install/BOOT-INF/lib' }
	from(layout.buildDirectory.dir('dependency/META-INF')) { into 'install/META-INF' }
	from(layout.buildDirectory.dir('dependency/BOOT-INF/classes')) { into 'install/BOOT-INF/classes' }
	doLast {
		println "Prepared Docker build context in 'build/docker/'"
	}
}

tasks.register('dockerBuildAmd64', Exec) {
	dependsOn tasks.named('prepareDockerContext')
	workingDir layout.buildDirectory.dir('docker').get().asFile

	def tagAmd64 = "${artifactoryUrl}/${artifactoryRealName}/${dockerImageName}:${project.version}"
	println "Building Docker image: ${tagAmd64}"

	commandLine "docker", "build", "--no-cache", "--platform=linux/amd64", ".",
			"-t", tagAmd64
}

tasks.register('dockerBuildArm64', Exec) {
	dependsOn tasks.named('prepareDockerContext')
	workingDir layout.buildDirectory.dir('docker').get().asFile

	def tagArm64 = "${artifactoryUrl}/${artifactoryRealName}/${dockerImageName}:${project.version}"
	println "Building Docker image: ${tagArm64}"

	commandLine "docker", "build", "--no-cache", '--platform=linux/arm64', ".",
			"-t", tagArm64
}