image: eclipse-temurin:21-jdk-noble

variables:
  GRADLE_USER_HOME: "${CI_PROJECT_DIR}/.gradle"
  INTERNAL_PREFIX: ""

default:
  cache:
    # Cache wrapper as long as properties are the same
    - paths:
        - .gradle/wrapper
      key:
        files:
          - gradle/wrapper/gradle-wrapper.properties
    # Cache Gradle cache for the current commit only
    - paths:
        - .gradle/caches
      key: ${CI_COMMIT_SHA}

stages:
  - test
  - build
  - vulnerability_scan
  - publish_config_zip
  - mirror

include:
  - component: ${CI_SERVER_FQDN}/application/generic-deployment-script/docker-build@fa155a9e146a915d1518747b59f53762cdf4f698
    inputs:
      stage: build

  # Scan internal images
  - component: ${CI_SERVER_FQDN}/application/generic-deployment-script/docker-scout@fa155a9e146a915d1518747b59f53762cdf4f698
    inputs:
      stage: vulnerability_scan
      image: "${JFROG_ARTIFACTORY_URL}/internal-${JFROG_REPOSITORY_REAL_NAME}/${DOCKER_IMAGE_NAME}:latest"

  - component: ${CI_SERVER_FQDN}/application/generic-deployment-script/publish-config-zip@fa155a9e146a915d1518747b59f53762cdf4f698
    inputs:
      stage: publish_config_zip

.base_prod:
  variables:
    INTERNAL_PREFIX: ""
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+/'
      when: on_success
    - when: never

.base_dev:
  variables:
    INTERNAL_PREFIX: "internal-"
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+/'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: on_success

test:
  stage: test
  extends: .base_dev
  tags:
    - Java
    - Docker
    - SpringBoot
  script:
    - ./gradlew clean test
  artifacts:
    when: always
    paths:
      - build/reports/tests/fireblocks-service/html
    reports:
      junit: "**/build/reports/tests/fireblocks-service/xml/*.xml"  # XML for GitLab Tests tab
    expire_in: 7 days

build_docker_prod:
  extends:
    - .docker_build
    - .base_prod
  script:
    - ./gradlew jib

build_docker_dev:
  extends:
    - .docker_build
    - .base_dev
  script:
    - ./gradlew jib

publish_config_zip:
  extends:
    - .publish_config_zip
    - .base_prod

mirror:
  stage: mirror
  tags:
    - SpringBoot
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_TAG
  # Mirror the main branch as-is to GitHub
  script:
    - git fetch --tags
    - git remote add github git@github.com:securosys-com/fireblocks-external-key-store.git || true
    - git push --tags --force github refs/remotes/origin/main:refs/heads/main
