// SPDX-FileCopyrightText: Copyright 2025 Securosys SA
// SPDX-License-Identifier: Apache-2.0

apply plugin: 'java'
apply plugin: 'idea'
apply plugin: 'io.freefair.lombok'

dependencies {
	implementation project(':fireblocks-datamodel')

	implementation libs.spring.boot.starter.web
	implementation libs.spring.boot.starter.data.jpa
	implementation libs.spring.boot.starter.validation
	implementation libs.spring.boot.starter.security
	implementation libs.spring.session.core

	implementation libs.commons.lang3
	implementation libs.commons.codec
	implementation libs.httpclient5
	implementation libs.springdoc.openapi.starter.webmvc.ui
	implementation libs.splunk.library.javalogging
	implementation libs.nimbus.jose.jwt
	implementation libs.nimbus.oauth2.oidc.sdk
	implementation libs.bouncycastle.bcprov
	implementation libs.bouncycastle.bcpkix
	implementation libs.bouncycastle.bcmail

	testImplementation libs.spring.boot.starter.test
	testImplementation libs.spring.security.test

	testImplementation libs.mariadb.java.client
	testImplementation libs.postgresql
	testImplementation libs.h2

	testImplementation libs.rest.assured
	testImplementation libs.rest.assured.spring.mock.mvc
	testImplementation libs.httpclient5
}

tasks.test {
    useJUnitPlatform()
}
